package com.example.sprint_modulo5

class ShoeList {
    companion object {
        fun getShoes(): List<Shoe> {
            val shoes = mutableListOf<Shoe>()
            shoes.add(Shoe(0, "Wild Rider Layers Unisex Sneakers", 121, "With design elements inspired by the movement and motion of city life, the Wild Rider Layers Unisex Sneakers brings a fresh new dimension to the iconic Rider family. We've layered a rich mix of premium leather, suede and hairy suede onto a nylon upper to create texture and a raw edgy look that is pure street. The IMEVA midsole and rubber outsole ensure combined lightweight comfort and great traction to take you forward, further and faster through your day and beyond.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/380697/02/sv01/fnd/IND/fmt/png/,Wild-Rider-Layers-Unisex-Sneakers" ))
            shoes.add(Shoe(1, "Mercedes Kart Cat-X Tech Unisex Sneakers", 151, "Premium material and tech features are given a branded boost from German engineering. The Mercedes Kart Cat-X Tech Unisex Sneakers areleant style and esteem by Mercedes-AMG Petronas Motorsport. The piece rises to the occasion with an all-leather upper.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/306557/01/sv01/fnd/IND/fmt/png/Mercedes-Kart-Cat-X-Tech-Unisex-Sneakers" ))
            shoes.add(Shoe(2, "Jako Slip-On Men's Shoes", 161, "The Jako Slip-On Men's Shoes are perfect for a laceless running style. Lightweight and styled for everyday wear, they feature a breathable and durable mesh upper. Layered cushioning adds comfort that goes the distance.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/381374/01/sv01/fnd/IND/fmt/png/Jako-Slip-On-Men's-Shoes" ))
            shoes.add(Shoe(3, "PUMA Serve Pro Lite Unisex shoes", 261, "Catering to the growing consumer expectation for casual, everyday comfort, the Serve Pro Lite Trainers feature shock-absorbing support for lightweight luxury.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/374902/01/sv01/fnd/IND/fmt/png/PUMA-Serve-Pro-Lite-Unisex-Shoes" ))
            shoes.add(Shoe(4, "Electron E Unisex Shoes", 321, "There's more to the Electron E Trainers than meets the eye. Its visible technology highlights fantastic features like a breathable mesh upper, synthetic quarter panels for support and a bold aesthetic that's both fun and futuristic. The elastic band on the heel provides extra comfort.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/380435/04/sv01/fnd/IND/fmt/png/Electron-E-Unisex-Shoes" ))
            shoes.add(Shoe(5, "one8 Virat Kohli Basket Classice Unisex Sneakers", 371, "This one is for the collectors,connoisseur & extreme uber cool, the one8 Virat Kohli Basket Classic one8 V3 pays homage to the illustrious career of the legend himslef", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/375314/01/sv01/fnd/IND/fmt/png/one8-Virat-Kohli-Basket-Classic-Unisex-Sneakers" ))
            shoes.add(Shoe(6, "Caracal SoftFoam+Sneakers", 171, "Long, clean lines, a premium leather upper and a tennis-inspired silhouette make the Caracal Sneakers your go-to for sleek style, whether you're on or off the court.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/369863/18/sv01/fnd/IND/fmt/png/Caracal-SoftFoam+-Sneakers" ))
            shoes.add(Shoe(7, "Mirage Mox Brightly Packed Shoes", 271, "The Mirage Mox takes design cues from a 1970s pair of PUMA running shoes and transforms them with textural contrasts, pops of colour and funky futuristic elements. Inspired by illusions and the space between what's real and otherworldly, it's ready for new realities. Incorporating caution tape elements for a deconstructed approach to this season's trends, the Brightly Packed iteration features premium materials for a sophisticated silhouette that will have you rocking retro with cool confidence", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/375168/01/sv01/fnd/IND/fmt/png/Mirage-Mox-Brightly-Packed-Shoes" ))
            shoes.add(Shoe(8, "Future Rider Play On Unisex Sneakers", 571, "Keep the game going in the shoe that launched a movement, our Future Rider Play On Unisex Sneakers. This shoe is dedicated to pared-down performance, featuring a super-light nylon, suede and leather upper and our famous shock-absorbing Federbein outsole to keep you pounding the pavement in style.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/371149/69/sv01/fnd/IND/fmt/png/Future-Rider-Play-On-Unisex-Sneakers" ))
            shoes.add(Shoe(9, "Anzarun Lite Unisex Sneakers", 671, "The freshest look for any occasion, the Anzarun Lite Trainers are PUMA's most refined shoe yet. Featuring the breezy Anzarun DNA mesh upper, a cushy SoftFoam+ sockliner and discreet PUMA branding throughout, you're sure to look great, wherever the day takes you.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/371128/23/sv01/fnd/IND/fmt/png/Anzarun-Lite-Unisex-Sneakers" ))
            shoes.add(Shoe(10, "Pacer Next Cage Shoes", 371, "With a foot-hugging mesh upper and a supportive lace-through midfoot caging system, the Pacer Next Cage has a sleek silhouette that is as ready for the gym as it is for the streets. A feather-light midsole provides superior energy return, cushioning and support, while slip-on construction adds a sock-like rather than a shoe-like feel. You wont want to leave home in anything else.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/365284/01/sv01/fnd/IND/fmt/png/Pacer-Next-Cage-Shoes" ))
            shoes.add(Shoe(11, "Rebound Lay-Up Lo SoftFoam+Mesh Shoes", 971, "Rethink the basketball trainer with the Rebound Lay-Up. This versatile sneaker features a mesh upper for superior breathability and a SoftFoam+ sockliner to give you a supportive fit. Paired with the iconic PUMA Formstrip, you will  have classic style with all of the innovation of today.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_600,h_600/global/370914/01/sv01/fnd/IND/fmt/png/Rebound-Lay-Up-Lo-SoftFoam+-Mesh-Shoes" ))
            shoes.add(Shoe(12, "one8 Virat Kohli Basket Classic Unisex Sneakers", 451, "This one is for the collectors,connoisseur & extreme uber cool, the one8 Virat Kohli Basket Classic one8 V3 pays homage to the illustrious career of the legend himslef", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/375314/02/sv01/fnd/IND/fmt/png/one8-Virat-Kohli-Basket-Classic-Unisex-Sneakers" ))
            shoes.add(Shoe(13, "PUMA x 1DER Columbus Men's Shoes", 271, "Crafted for the ones who love an active life while looking stylish, PUMA and KL Rahul bring you the Columbus Men's Shoes. Enveloping KL Rahul's bold and sophisticated style, the contrasting overlays add edge to the overall look of PUMA x 1DER Columbus Men's Shoes. Even though the PUMA and 1DER logos are subtle, they are unmissable.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_2000,h_2000/global/387768/01/sv01/fnd/IND/fmt/png/PUMA-x-1DER-Columbus-Men's-Shoes" ))
            shoes.add(Shoe(14, "BMW M Motorsport City Rider Sneakers", 556, "Live life grand with the BMW M Motorsport City Rider Unisex Sneakers. Featuring the signature Rider outsole in combination with the BMW branding. The stunning design adds the edge that'll make any casual look appear out of the world", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/306975/01/sv01/fnd/IND/fmt/png/BMW-M-Motorsport-City-Rider-Sneakers" ))
            shoes.add(Shoe(15, "Jamming FUSEFIT Evolution Shoes", 771, "Inspired by Spacewalk, the Jamming FUSEFIT Evolution Sneakers take the next step in futuristic design and technology. The combined outsole features a TPU membrane that encapsulates free-floating EVA beads for superior cushioning and the feeling of walking on sand. A unique lacing system gives you endless possibilities for comfort and style. With versatile and adaptive features, these sneakers are the perfect way to overcome any obstacle and propel yourself into new worlds.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/366545/01/sv01/fnd/IND/fmt/png/Jamming-FUSEFIT-Evolution-Shoes" ))
            shoes.add(Shoe(16, "Puma Perforated Low Men's Shoes", 871, "Be street ready with the Puma Perforated Low Men's Shoes perfect for leisure and slaying around.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1050,h_1050/global/372981/01/sv01/fnd/IND/fmt/png/Puma-Perforated-Low-Men's--IDP-Shoes" ))
            shoes.add(Shoe(17, "RS-X TOYS Unisex Sneakers", 971, "Based on PUMAs innovative Running System technology, the RS-X line draws its design inspiration from the decade that had the best toys ever, hands down, bar none: the 1980s. Specifically, these RS-X TOYS Unisex Sneakers play on the trend of the toys of our childhood ultimately becoming collectors items down the road. The mesh upper on these Sneakers promote air flow, and features colours that would be at home in a crowded video arcade from 30 years ago. A unique cushioning function provides support, and the rubber outsole offers supreme traction and grip.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/369449/24/sv01/fnd/IND/fmt/png/RS-X-TOYS-Unisex-Sneakers" ))
            shoes.add(Shoe(18, "X-RAY� Ramble Unisex Shoes", 271, "Take to the urban outdoors in the X-Ray� Ramble Trainers. PUMAs signature street style just got rugged, with technical fabrics like ripstop and suede, robust eyestay webbing straps and discreet branding. So, of course, the shoe looks fierce - but with the full-on comfort of Softfoam+, this hiking hybrid feels amazing too.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_750,h_750/global/380727/06/sv01/fnd/IND/fmt/png/X-RAY%C2%B2-Ramble-Unisex-Shoes" ))
            shoes.add(Shoe(19, "RS-X� Twill Air Mesh Shoes", 171, "Dare to be bold. We've rebooted the RS design to take it to a whole new level. We've stripped it back to down basics and rebuilding it with more extreme mixes of colour and materials for a 3x stronger retro-meets-the-future look. PUMA's Running System is the engine under the bonnet, providing comfort and cushioning with every step.", "https://images.puma.com/image/upload/f_auto,q_auto,b_rgb:fafafa,w_1500,h_1500/global/368845/02/sv01/fnd/IND/fmt/png/RS-X%C2%B3-Twill-Air-Mesh-Shoes" ))
            shoes.add(Shoe(20, "Sl 20.2 Shoes", 871, "Dare to be bold. We've rebooted the RS design to take it to a whole new level. We've stripped it back to down basics and rebuilding it with more extreme mixes of colour and materials for a 3x stronger retro-meets-the-future look. PUMA's Running System is the engine under the bonnet, providing comfort and cushioning with every step.", "https://assets.adidas.com/images/w_600,f_auto,q_auto/ad53e2abade1464bb0dcad0c00aaafec_9366/SL20.2_Shoes_Orange_Q46187_01_standard.jpg" ))
            shoes.add(Shoe(21, "ZX 2K Boost 2.0 Trail Shoes", 571, "The daily commute. The walk to the coffee shop. The off hours when you're free to roam. When life takes you out into the city, these adidas shoes help you cruise. Built on the innovative ZX line and infused with the technical vibe of trail shoes, they have a responsive Boost midsole, a grippy outsole and a warm lining. We're talking all-day comfort here.", "https://assets.adidas.com/images/w_600,f_auto,q_auto/06dcf7e2969045b48da6ad5500f501bf_9366/ZX_2K_Boost_2.0_Trail_Shoes_Green_GZ7784_01_standard.jpg" ))
            shoes.add(Shoe(22, "PREDATOR FREAK .3 FG J", 1571, "Dare to be bold. We've rebooted the RS design to take it to a whole new level. We've stripped it back to down basics and rebuilding it with more extreme mixes of colour and materials for a 3x stronger retro-meets-the-future look.", "https://assets.adidas.com/images/w_600,f_auto,q_auto/ae95d399b7d446a4afd7ac7700d4d30d_9366/PREDATOR_FREAK_.3_FG_J_Black_FW7530_01_standard.jpg" ))
            shoes.add(Shoe(23, "Defiant Generation multicourt tennis shoes", 971, "Who says you can't have it all? Lace up these adidas Defiant Generation tennis shoes to raise your game. The foot-hugging upper and cushioned midsole combine to keep you comfortable as you express yourself on the court. The durable outsole and abrasion-resistant toe easily stand up to your all-action game.", "https://assets.adidas.com/images/w_600,f_auto,q_auto/49a9781d4d9c46629e9dabad00dd154b_9366/Defiant_Generation_multicourt_tennis_shoes_Pink_FX5814_01_standard.jpg" ))
            shoes.add(Shoe(24, "Air Jordan XXXVI Low", 126, "Lace up in the energy that sparked a basketball revolution. One of the lightest Air Jordan game shoes to date, the AJ XXXVI features a minimal but durable upper with reinforcing overlay. It also comes equipped with Zoom Air cushioning for added responsiveness. Step on to the court with the confidence that whatever you do�it's light work.", "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/72d2a488-a065-47a1-bf66-e8adfe0ba1f7/air-jordan-xxxvi-low-mens-basketball-shoes-LgcvQl.png" ))
            shoes.add(Shoe(25, "Air Jordan XXXVI Tatum", 200, "From the perimeter to the hoop, take the court with confidence. This is one of the lightest on-court Air Jordans to date, with a minimal-yet-durable upper reinforced with tough plastic details. Meanwhile, Zoom Air cushioning delivers energy return and elite responsiveness. The game asks for everything�now you have the shoes to match.", "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/ea16d7c4-7d1c-444c-bda7-1a4f32770935/air-jordan-xxxvi-tatum-mens-basketball-shoes-0jD1F6.png" ))
            shoes.add(Shoe(26, "Air Jordan XXXVI 'Taco Jay'", 200, "Prep for the game by lacing up your AJs, win the game by channeling the heat of �Taco Jay.� The 36th generation of Air Jordan celebrates the newest superstars to build the game, and this model is all about Jayson Tatum. Bridging tunnel style with performance tech, the design pays homage to Jay's intensity on the court�and fiery hot-sauce-and-cheese inspired colors nod to his favorite post-game food.", "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/6e348a2f-e547-479a-af13-38c624e7e9e8/air-jordan-xxxvi-taco-jay-mens-basketball-shoes-zv2DcC.png" ))
            shoes.add(Shoe(27, "Air Jordan 7 Retro", 200, "Inspired by the shoe originally worn by MJ during the '92 season and summer of basketball, the Air Jordan 7 Retro revives its championship legacy for a new generation of sneakerheads.", "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/bd3da02f-2ddc-4f0c-bb7b-f94c634cc0dd/air-jordan-7-retro-mens-shoes-7Zr804.png" ))
            shoes.add(Shoe(28, "Air Jordan 1 Utility", 170, "Utilitarian, but make it edgy: these AJ1s give you functional use without compromising that style you know and love. Tough canvas, stash pockets and webbing pulls give these classic kicks a hit of rugged versatility.", "https://static.nike.com/a/images/c_limit,w_592,f_auto/t_product_v1/956b0723-ef2f-4b49-8982-e2ec37e14f9c/air-jordan-1-utility-mens-shoes.png" ))
            shoes.add(Shoe(29, "Air Jordan 6 Retro", 200, "MJ's sixth signature shoe debuted during the 1990-1991 season as His Airness battled rivals in pursuit of an elusive first championship. Now, it's back in a variety of color schemes. Gear up for the 30th anniversary of the Air Jordan 6 with this timeless classic.", "https://static.nike.com/a/images/t_PDP_864_v1/f_auto,b_rgb:f5f5f5/17fde102-11ef-4592-ad9a-795b667ed2cb/air-jordan-6-retro-shoes-vXk3FV.png" ))


            return shoes
        }
    }
}